# Generated by Django 4.0.4 on 2022-06-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('descritption', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
