# Generated by Django 4.0.4 on 2022-06-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mifumoweb', '0002_service_created_at_alter_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('slug', models.SlugField(null=True)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
